name: Build & Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  build_and_test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']

    name: Node on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    timeout-minutes: 30
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version-file: '../package.json'
      - uses: actions/checkout@v1
      - name: Restore Dependency Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm ci

      - name: Setup Testing Environment
        run: npm run bootstrap

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
  format:
    name: Format
    uses: ./.github/workflows/format.yml
